# -*- coding: utf-8 -*-
"""generate_feedback

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfx71VqF0llhr_N9VKmEU8WHfHKTSqxA
"""

"""
Use local LLM (like Mistral-7B via Transformers or LM Studio API) to convert score into natural language summary.
"""
import pandas as pd

def score_to_text(score):
    if score > 0.6:
        return "You are currently showing signs of high stress across multiple modalities. Consider taking a break or using relaxation techniques."
    elif score > 0.2:
        return "Mild to moderate stress detected. Stay mindful and take care of your mental state."
    else:
        return "No significant stress indicators detected. You're doing well!"

def generate_feedback():
    df = pd.read_excel("exports/fused_stress_scores.xlsx")
    df["Narrative Feedback"] = df["Fused Stress Score"].apply(score_to_text)
    df.to_excel("exports/stress_feedback_with_narrative.xlsx", index=False)
    print("Feedback saved to exports/stress_feedback_with_narrative.xlsx.")

if __name__ == "__main__":
    generate_feedback()